import XCTest

final class LayeringPlanDocumentationTests: XCTestCase {
    func testLayeringPlanDocumentsSplitBoundariesWhenDocsAreAvailable() throws {
        let root = repositoryRoot()
        try skipIfDocumentationIsUnavailable(root: root)
        let planURL = root.appendingPathComponent("doc/Architecture/Layering_Refactor_Plan.md")
        XCTAssertTrue(
            FileManager.default.fileExists(atPath: planURL.path),
            "Missing documentation artifact: doc/Architecture/Layering_Refactor_Plan.md"
        )
        let plan = try String(contentsOf: planURL, encoding: .utf8)

        XCTAssertTrue(plan.contains("MediaLibCore"))
        XCTAssertTrue(plan.contains("DetailNavigationStore"))
        XCTAssertTrue(plan.contains("VideoCollectionStore"))
        XCTAssertTrue(plan.contains("QuickPreviewStore"))
        XCTAssertTrue(plan.contains("AppUpdateStateStore"))
        XCTAssertTrue(plan.contains("SponsorPromptStore"))
        XCTAssertTrue(plan.contains("NetworkStreamPromptStore"))
        XCTAssertTrue(plan.contains("VideoManualCollectionCreationStore"))
        XCTAssertTrue(plan.contains("VideoOfflineSubscriptionLimitStore"))
        XCTAssertTrue(plan.contains("EmbyRestrictionNoticeStore"))
        XCTAssertTrue(plan.contains("StartupErrorStore"))
        XCTAssertTrue(plan.contains("TMDBMatchStateStore"))
        XCTAssertTrue(plan.contains("MusicMetadataActivityStore"))
        XCTAssertTrue(plan.contains("PrivacyLockStateStore"))
        XCTAssertTrue(plan.contains("FloatingNoticeStore"))
        XCTAssertTrue(plan.contains("SakuraEasterEggStateStore"))
        XCTAssertTrue(plan.contains("OnboardingReplayStore"))
        XCTAssertTrue(plan.contains("LastfmAuthorizationStateStore"))
        XCTAssertTrue(plan.contains("TraktSyncActivityStore"))
        XCTAssertTrue(plan.contains("ThemeRefreshStore"))
        XCTAssertTrue(plan.contains("MediaSearchIndexStateStore"))
        XCTAssertTrue(plan.contains("TaskCenterStore"))
        XCTAssertTrue(plan.contains("ScanActivityStore"))
        XCTAssertTrue(plan.contains("MusicQueueStore"))
        XCTAssertTrue(plan.contains("PlaybackSessionStore"))
        XCTAssertTrue(plan.contains("LibraryDomainStore"))
        XCTAssertTrue(plan.contains("RemoteConnectorStore"))
        XCTAssertTrue(plan.contains("PlaybackQueuePolicy"))
        XCTAssertTrue(plan.contains("PlaybackTimelinePolicy"))
        XCTAssertTrue(plan.contains("PlaybackSeekState"))
        XCTAssertTrue(plan.contains("PlaybackClockPolicy"))
        XCTAssertTrue(plan.contains("PlaybackSeekCoordinator"))
        XCTAssertTrue(plan.contains("PendingPlaybackSeek"))
        XCTAssertTrue(plan.contains("PlaybackSeekCommandPolicy"))
        XCTAssertTrue(plan.contains("PlaybackClockSnapshot"))
        XCTAssertTrue(plan.contains("MusicOutputPolicy"))
        XCTAssertTrue(plan.contains("MusicPlaybackBufferPolicy"))
        XCTAssertTrue(plan.contains("PerceptualVolumeScale"))
        XCTAssertTrue(plan.contains("CyclicModePolicy"))
        XCTAssertTrue(plan.contains("PlaybackABLoopPolicy"))
        XCTAssertTrue(plan.contains("PlayerABLoopSelection"))
        XCTAssertTrue(plan.contains("双向轮换"))
        XCTAssertTrue(plan.contains("VideoPlaybackControlling"))
        XCTAssertTrue(plan.contains("VideoPlaybackStateProjecting"))
        XCTAssertTrue(plan.contains("MpvTrack"))
        XCTAssertTrue(plan.contains("MpvVideoSnapshotReader"))
        XCTAssertTrue(plan.contains("TrackLanguageMatcher"))
        XCTAssertTrue(plan.contains("MemoryAudioAsset"))
        XCTAssertTrue(plan.contains("VideoAudioFilterPolicy"))
        XCTAssertTrue(plan.contains("VideoFilterChainPolicy"))
        XCTAssertTrue(plan.contains("VideoSubtitleStylePolicy"))
        XCTAssertTrue(plan.contains("VideoColorAdjustmentPolicy"))
        XCTAssertTrue(plan.contains("VideoDebandPolicy"))
        XCTAssertTrue(plan.contains("VideoPlaybackPropertyPolicy"))
        XCTAssertTrue(plan.contains("VideoToneMappingPolicy"))
        XCTAssertTrue(plan.contains("VideoTimingAdjustmentPolicy"))
        XCTAssertTrue(plan.contains("VideoPitchCorrectionPolicy"))
        XCTAssertTrue(plan.contains("VideoPlaybackEngine"))
        XCTAssertTrue(plan.contains("VideoTrackSelectionEngine"))
        XCTAssertTrue(plan.contains("VideoFrameCommandEngine"))
        XCTAssertTrue(plan.contains("VideoScreenshotModePolicy"))
        XCTAssertTrue(plan.contains("VideoLoopCommandEngine"))
        XCTAssertTrue(plan.contains("VideoAudioDeviceReader"))
        XCTAssertTrue(plan.contains("MusicPlaybackEngine"))
        XCTAssertTrue(plan.contains("防 god object"))
    }

    private func skipIfDocumentationIsUnavailable(root: URL) throws {
        let docsDirectory = root.appendingPathComponent("doc", isDirectory: true)
        guard FileManager.default.fileExists(atPath: docsDirectory.path) else {
            throw XCTSkip("doc/ is not available in this environment; documentation checks are local-only.")
        }
    }

    private func repositoryRoot() -> URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
    }
}
