import Foundation
import MediaLibCore

enum AppLocalizer {
    static func text(_ key: String, language: AppLanguage) -> String {
        guard language != .zhHans else { return key }
        return translations[language]?[key] ?? key
    }

    private static let translations: [AppLanguage: [String: String]] = [
        .en: [
            "设置": "Settings",
            "调整播放、媒体库、界面与隐私设置。": "Tune playback, your library, the interface, and privacy.",
            "外观与布局": "Appearance & Layout",
            "调整主题、配色和海报尺寸。": "Adjust the theme, colors, and poster sizing.",
            "语言": "Language",
            "界面语言": "Interface language",
            "切换后会在下次启动时完整生效，当前窗口会先更新设置页和提示文案。": "The full interface changes after the next launch. This page and notices update right away.",
            "主题": "Theme",
            "跟随系统": "Use system",
            "深色": "Dark",
            "浅色": "Light",
            "内置": "Built-in",
            "系统": "System",
            "关闭": "Off",
            "开启": "On",
            "自动": "Automatic",
            "标准": "Standard",
            "宽松": "Relaxed",
            "严格": "Strict",
            "兼容": "Compatible",
            "自动下一集": "Play next episode",
            "停在结尾": "Hold last frame",
            "关闭窗口": "Close window",
            "流畅优先": "Performance",
            "画面优先": "Image quality",
            "截取视频帧": "Use video frame",
            "绘制默认封面": "Draw default artwork",
            "不生成": "Do not generate",
            "原词逐字": "Original word-by-word",
            "音频对齐": "Audio-aligned",
            "估算同步": "Estimated sync",
            "关闭均衡": "Off",
            "曲目": "Track",
            "专辑": "Album",
            "立即切换": "Immediate",
            "柔和淡入": "Soft fade",
            "每 15 分钟": "Every 15 minutes",
            "每小时": "Hourly",
            "每 6 小时": "Every 6 hours",
            "每天": "Daily",
            "MusicBrainz": "MusicBrainz",
            "iTunes Search": "iTunes Search",
            "网易云音乐": "NetEase Cloud Music",
            "QQ 音乐": "QQ Music",
            "清蓝": "Clear blue",
            "珊瑚": "Coral",
            "青柠": "Lime",
            "暖杏": "Apricot",
            "夜幕": "Night",
            "自定义": "Custom",
            "配色": "Color style",
            "底色 / 卡片": "Base / cards",
            "高亮色": "Accent",
            "左上角光线": "Upper-left light",
            "海报最小宽度": "Min poster width",
            "海报最大宽度": "Max poster width",
            "新手引导": "Welcome guide",
            "重新查看引导…": "View guide again...",
            "视频播放与缓存": "Video Playback & Cache",
            "设置视频启动方式、观看规则和离线缓存。": "Choose how videos open, when they count as watched, and how offline cache works.",
            "启动方式": "Opening",
            "视频播放器": "Video player",
            "视频系统播放器": "System video player",
            "系统默认视频播放器": "Default video app",
            "设为默认": "Set default",
            "选择…": "Choose...",
            "默认": "Default",
            "观看规则": "Watching",
            "记忆播放进度": "Remember progress",
            "播放完成自动标记已看": "Mark watched at the end",
            "播放结束行为": "When playback ends",
            "已看判定": "Watched threshold",
            "离线缓存": "Offline cache",
            "视频缓存位置": "Video cache location",
            "视频缓存占用": "Video cache usage",
            "缓存容量上限": "Cache limit",
            "不限制": "No limit",
            "音乐播放": "Music Playback",
            "设置音乐播放器、歌词、响度和过渡。": "Set up the music player, lyrics, loudness, and transitions.",
            "音乐播放器": "Music player",
            "音乐系统播放器": "System music player",
            "系统默认音乐播放器": "Default music app",
            "歌词同步": "Lyric sync",
            "封面发光": "Album glow",
            "音乐响度均衡": "Loudness leveling",
            "跨曲过渡": "Track transition",
            "淡入时长": "Fade-in length",
            "均衡器": "Equalizer",
            "均衡器预设": "EQ preset",
            "自动扫描与封面": "Auto Scan & Artwork",
            "设置后台扫描、封面补全和截图规则。": "Set background scans, artwork fallback, and thumbnail rules.",
            "自动扫描": "Auto scan",
            "完成后发送通知": "Notify when finished",
            "缺失封面处理": "Missing artwork",
            "避开黑屏": "Avoid black frames",
            "截图位置": "Frame position",
            "并发截图任务": "Thumbnail jobs",
            "元数据与在线服务": "Metadata & Online Services",
            "设置 TMDB、音乐元数据和自动补充。": "Set up TMDB, music metadata, and automatic matching.",
            "影片信息": "Video metadata",
            "TMDB API": "TMDB API",
            "TMDB 语言": "TMDB language",
            "影视匹配宽容度": "Video match tolerance",
            "剧集一键匹配": "Batch match series",
            "自动拉取周期": "Auto fetch interval",
            "音乐信息": "Music metadata",
            "音乐数据源": "Music source",
            "音乐匹配宽容度": "Music match tolerance",
            "音乐增量补充": "Fill missing music info",
            "音乐元数据获取": "Music metadata tool",
            "字幕": "Subtitles",
            "设置字幕搜索语言和 OpenSubtitles 账号。": "Set subtitle search language and OpenSubtitles access.",
            "首选语言": "Preferred language",
            "账号与同步状态": "Accounts & Sync",
            "查看远程账号、同步冲突和元数据历史。": "Review remote accounts, sync conflicts, and metadata history.",
            "远程账号": "Remote accounts",
            "同步冲突": "Sync conflicts",
            "元数据历史": "Metadata history",
            "查看": "View",
            "Trakt 同步": "Trakt Sync",
            "同步已看 / 想看，并可从 Trakt 导入差异到冲突队列。": "Sync watched and watchlist states, and review Trakt differences before applying them.",
            "账号连接": "Account",
            "启用同步": "Enable sync",
            "从 Trakt 导入": "Import from Trakt",
            "保险库": "Vault",
            "管理私密内容的解锁方式。": "Manage how private content is unlocked.",
            "数据、存储与诊断": "Data, Storage & Diagnostics",
            "管理备份、存储位置、清理和性能记录。": "Manage backups, storage paths, cleanup, and performance logs.",
            "性能记录": "Performance log",
            "数据库版本": "Database version",
            "数据库备份": "Database backup",
            "立即备份": "Back up now",
            "从备份恢复…": "Restore backup...",
            "打开位置": "Open folder",
            "数据库位置": "Database path",
            "备份位置": "Backup path",
            "缓存位置": "Cache path",
            "空间整理": "Storage cleanup",
            "一键清理": "Clean up",
            "关于软件": "About",
            "查看项目地址、作者和联系方式。": "View the project, author, and contact details.",
            "关于 MediaLIB": "About MediaLIB",
            "MediaLIB 是一款面向 macOS 的个人影音媒体库应用，帮助你整理、播放和管理本地、Emby 与网络来源的视频和音乐收藏。": "MediaLIB is a personal media library for macOS. It helps you organize, play, and manage videos and music from local folders, Emby, and network sources.",
            "作者": "Author",
            "投喂作者": "Support the author",
            "请作者喝杯咖啡": "Buy me a coffee",
            "关闭按钮": "Close",
            "查看关于…": "About MediaLIB...",
            "软件更新": "Software update",
            "更新提醒": "Update reminders",
            "恢复自动提醒": "Turn reminders back on",
            "当前版本": "Current version",
            "后台更新检查只读取 GitHub Releases 元数据；跳过当前版本后，静默检查不会再提示这一版，手动检查仍可看到结果。": "Background checks only read GitHub Releases metadata. If you skip this version, quiet checks will stop showing it; manual checks still work.",
            "检查更新": "Check for updates",
            "检查中…": "Checking...",
            "正在检查更新": "Checking for updates",
            "MediaLIB 正在后台确认最新版本，请稍等。": "MediaLIB is checking the latest version in the background.",
            "已是最新版本": "You're up to date",
            "检查更新失败": "Could not check for updates",
            "发现新版本": "Update available",
            "跳过此版": "Skip this version",
            "不再自动提醒": "Stop automatic reminders",
            "打开 Release": "Open release",
            "下载更新": "Download update",
            "更新内容": "What's new",
            "发布日期": "Released",
            "此版本未提供更新日志，可前往 Release 页面查看详情。": "No release notes were provided. You can still open the release page for details.",
            "觉得软件不错？投喂我！": "Enjoying MediaLIB?",
            "MediaLIB 由我一个人利用业余时间打磨。如果它帮到了你，一杯咖啡的鼓励能让它走得更远。": "MediaLIB is built in my spare time. If it has helped you, your support keeps it moving forward.",
            "下次一定": "Maybe later",
            "现在就去！": "Support now"
        ],
        .ja: [
            "设置": "設定",
            "调整播放、媒体库、界面与隐私设置。": "再生、ライブラリ、画面表示、プライバシーを調整します。",
            "外观与布局": "外観とレイアウト",
            "调整主题、配色和海报尺寸。": "テーマ、配色、ポスターサイズを調整します。",
            "语言": "言語",
            "界面语言": "表示言語",
            "切换后会在下次启动时完整生效，当前窗口会先更新设置页和提示文案。": "完全な切り替えは次回起動後に反映されます。設定画面と通知はすぐに更新されます。",
            "主题": "テーマ",
            "跟随系统": "システムに合わせる",
            "深色": "ダーク",
            "浅色": "ライト",
            "内置": "内蔵",
            "系统": "システム",
            "关闭": "オフ",
            "开启": "オン",
            "自动": "自動",
            "标准": "標準",
            "宽松": "ゆるめ",
            "严格": "厳密",
            "兼容": "互換",
            "自动下一集": "次のエピソードを再生",
            "停在结尾": "最後のフレームで停止",
            "关闭窗口": "ウィンドウを閉じる",
            "流畅优先": "滑らかさ優先",
            "画面优先": "画質優先",
            "截取视频帧": "動画フレームを使う",
            "绘制默认封面": "既定アートワークを描く",
            "不生成": "生成しない",
            "原词逐字": "元歌詞・逐語",
            "音频对齐": "音声に合わせる",
            "估算同步": "推定同期",
            "关闭均衡": "オフ",
            "曲目": "トラック",
            "专辑": "アルバム",
            "立即切换": "すぐ切り替え",
            "柔和淡入": "やわらかくフェード",
            "每 15 分钟": "15 分ごと",
            "每小时": "毎時",
            "每 6 小时": "6 時間ごと",
            "每天": "毎日",
            "MusicBrainz": "MusicBrainz",
            "iTunes Search": "iTunes Search",
            "网易云音乐": "NetEase Cloud Music",
            "QQ 音乐": "QQ Music",
            "清蓝": "クリアブルー",
            "珊瑚": "コーラル",
            "青柠": "ライム",
            "暖杏": "アプリコット",
            "夜幕": "ナイト",
            "自定义": "カスタム",
            "配色": "カラースタイル",
            "底色 / 卡片": "ベース / カード",
            "高亮色": "アクセント",
            "左上角光线": "左上の光",
            "海报最小宽度": "ポスター最小幅",
            "海报最大宽度": "ポスター最大幅",
            "新手引导": "はじめてガイド",
            "重新查看引导…": "ガイドをもう一度見る...",
            "视频播放与缓存": "動画再生とキャッシュ",
            "设置视频启动方式、观看规则和离线缓存。": "動画の開き方、視聴判定、オフラインキャッシュを設定します。",
            "启动方式": "起動方法",
            "视频播放器": "動画プレーヤー",
            "视频系统播放器": "システム動画プレーヤー",
            "系统默认视频播放器": "既定の動画アプリ",
            "设为默认": "既定にする",
            "选择…": "選択...",
            "默认": "既定",
            "观看规则": "視聴ルール",
            "记忆播放进度": "再生位置を記憶",
            "播放完成自动标记已看": "最後まで再生したら視聴済みにする",
            "播放结束行为": "再生終了時",
            "已看判定": "視聴済み判定",
            "离线缓存": "オフラインキャッシュ",
            "视频缓存位置": "動画キャッシュの場所",
            "视频缓存占用": "動画キャッシュ使用量",
            "缓存容量上限": "キャッシュ上限",
            "不限制": "制限なし",
            "音乐播放": "音楽再生",
            "设置音乐播放器、歌词、响度和过渡。": "音楽プレーヤー、歌詞、音量補正、曲間を設定します。",
            "音乐播放器": "音楽プレーヤー",
            "音乐系统播放器": "システム音楽プレーヤー",
            "系统默认音乐播放器": "既定の音楽アプリ",
            "歌词同步": "歌詞同期",
            "封面发光": "ジャケットの光",
            "音乐响度均衡": "音量をそろえる",
            "跨曲过渡": "曲間の切り替え",
            "淡入时长": "フェード時間",
            "均衡器": "イコライザー",
            "均衡器预设": "EQ プリセット",
            "自动扫描与封面": "自動スキャンとアートワーク",
            "设置后台扫描、封面补全和截图规则。": "バックグラウンドスキャン、アートワーク補完、サムネイル規則を設定します。",
            "自动扫描": "自動スキャン",
            "完成后发送通知": "完了時に通知",
            "缺失封面处理": "アートワークがない時",
            "避开黑屏": "黒画面を避ける",
            "截图位置": "サムネイル位置",
            "并发截图任务": "サムネイル処理数",
            "元数据与在线服务": "メタデータとオンラインサービス",
            "设置 TMDB、音乐元数据和自动补充。": "TMDB、音楽メタデータ、自動補完を設定します。",
            "影片信息": "動画メタデータ",
            "TMDB API": "TMDB API",
            "TMDB 语言": "TMDB 言語",
            "影视匹配宽容度": "動画マッチ許容度",
            "剧集一键匹配": "シリーズ一括マッチ",
            "自动拉取周期": "自動取得間隔",
            "音乐信息": "音楽メタデータ",
            "音乐数据源": "音楽データ源",
            "音乐匹配宽容度": "音楽マッチ許容度",
            "音乐增量补充": "音楽情報の補完",
            "音乐元数据获取": "音楽メタデータ取得",
            "字幕": "字幕",
            "设置字幕搜索语言和 OpenSubtitles 账号。": "字幕検索の言語と OpenSubtitles を設定します。",
            "首选语言": "優先言語",
            "账号与同步状态": "アカウントと同期",
            "查看远程账号、同步冲突和元数据历史。": "リモートアカウント、同期の競合、メタデータ履歴を確認します。",
            "远程账号": "リモートアカウント",
            "同步冲突": "同期の競合",
            "元数据历史": "メタデータ履歴",
            "查看": "表示",
            "Trakt 同步": "Trakt 同期",
            "同步已看 / 想看，并可从 Trakt 导入差异到冲突队列。": "視聴済み / 見たいを同期し、Trakt との差分は確認してから反映できます。",
            "账号连接": "アカウント",
            "启用同步": "同期を有効化",
            "从 Trakt 导入": "Trakt から読み込む",
            "保险库": "保管庫",
            "管理私密内容的解锁方式。": "プライベートコンテンツの解除方法を管理します。",
            "数据、存储与诊断": "データ、保存先、診断",
            "管理备份、存储位置、清理和性能记录。": "バックアップ、保存先、整理、性能ログを管理します。",
            "性能记录": "性能ログ",
            "数据库版本": "データベース版",
            "数据库备份": "データベースバックアップ",
            "立即备份": "今すぐバックアップ",
            "从备份恢复…": "バックアップから復元...",
            "打开位置": "場所を開く",
            "数据库位置": "データベースの場所",
            "备份位置": "バックアップの場所",
            "缓存位置": "キャッシュの場所",
            "空间整理": "ストレージ整理",
            "一键清理": "整理する",
            "关于软件": "このアプリについて",
            "查看项目地址、作者和联系方式。": "プロジェクト、作者、連絡先を確認できます。",
            "关于 MediaLIB": "MediaLIB について",
            "MediaLIB 是一款面向 macOS 的个人影音媒体库应用，帮助你整理、播放和管理本地、Emby 与网络来源的视频和音乐收藏。": "MediaLIB は macOS 向けの個人用メディアライブラリです。ローカル、Emby、ネットワーク上の動画や音楽を整理し、再生し、管理できます。",
            "作者": "作者",
            "投喂作者": "作者を応援",
            "请作者喝杯咖啡": "コーヒーで応援する",
            "关闭按钮": "閉じる",
            "查看关于…": "MediaLIB について...",
            "软件更新": "ソフトウェア更新",
            "更新提醒": "更新通知",
            "恢复自动提醒": "通知を再開",
            "当前版本": "現在のバージョン",
            "后台更新检查只读取 GitHub Releases 元数据；跳过当前版本后，静默检查不会再提示这一版，手动检查仍可看到结果。": "バックグラウンド確認では GitHub Releases のメタデータだけを読み込みます。このバージョンをスキップすると静かな確認では表示されませんが、手動確認では引き続き確認できます。",
            "检查更新": "更新を確認",
            "检查中…": "確認中...",
            "正在检查更新": "更新を確認中",
            "MediaLIB 正在后台确认最新版本，请稍等。": "MediaLIB がバックグラウンドで最新版を確認しています。",
            "已是最新版本": "最新版です",
            "检查更新失败": "更新を確認できませんでした",
            "发现新版本": "新しいバージョンがあります",
            "跳过此版": "このバージョンをスキップ",
            "不再自动提醒": "自動通知を止める",
            "打开 Release": "Release を開く",
            "下载更新": "更新をダウンロード",
            "更新内容": "更新内容",
            "发布日期": "公開日",
            "此版本未提供更新日志，可前往 Release 页面查看详情。": "このバージョンには更新ログがありません。Release ページで詳細を確認できます。",
            "觉得软件不错？投喂我！": "MediaLIB、気に入ってくれましたか？",
            "MediaLIB 由我一个人利用业余时间打磨。如果它帮到了你，一杯咖啡的鼓励能让它走得更远。": "MediaLIB は個人で少しずつ磨いているアプリです。役に立ったなら、応援してもらえるとこれからも続けられます。",
            "下次一定": "また今度",
            "现在就去！": "応援する"
        ]
    ]
}

extension AppLanguage {
    var localeIdentifier: String {
        switch self {
        case .zhHans: return "zh-Hans"
        case .en: return "en"
        case .ja: return "ja"
        }
    }
}

extension AppState {
    func localized(_ key: String) -> String {
        AppLocalizer.text(key, language: settings.appLanguage)
    }

    var sponsorURL: URL {
        switch settings.appLanguage {
        case .zhHans:
            return URL(string: "https://ifdian.net/a/0521zn/plan")!
        case .en, .ja:
            return URL(string: "https://www.patreon.com/c/feiniaoqianshan/membership")!
        }
    }
}
