// Generated by scripts/release_metadata.py from config/release.json.
// Do not edit this file directly.

public enum GeneratedReleaseMetadata {
    public static let productVersion = "1.8.0"
    public static let buildNumber = "98"
    public static let releaseChannel = "stable"
    public static let isPrerelease = false
}
