#!/usr/bin/env python3
"""Generate and verify product release metadata.

This tool owns the product marketing version, build number, development
fallback constants, README badges, and packaged Info.plist version fields.
It deliberately does not read or modify database schema, API protocol, or web
asset cache versions.
"""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import plistlib
import re
import sys
import tempfile


CONFIG_KEYS = {"productVersion", "buildNumber", "releaseChannel"}
VERSION_PATTERN = re.compile(r"^[0-9]+(?:\.[0-9]+){1,3}$")
BUILD_PATTERN = re.compile(r"^[1-9][0-9]*$")
README_MARKER = "<!-- release-version-badge: generated from config/release.json -->"
README_BADGES = {
    "README.md": "![版本](https://img.shields.io/badge/版本-{version}-34C759?style=flat-square)",
    "README.en.md": "![Version](https://img.shields.io/badge/Version-{version}-34C759?style=flat-square)",
    "README.ja.md": "![バージョン](https://img.shields.io/badge/バージョン-{version}-34C759?style=flat-square)",
}


class MetadataError(ValueError):
    pass


def load_metadata(root: pathlib.Path) -> dict[str, str]:
    config_path = root / "config" / "release.json"
    try:
        value = json.loads(config_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise MetadataError(f"cannot read {config_path}: {error}") from error
    if not isinstance(value, dict) or set(value) != CONFIG_KEYS:
        raise MetadataError(
            "release.json must contain exactly productVersion, buildNumber, and releaseChannel"
        )
    if not all(isinstance(value[key], str) for key in CONFIG_KEYS):
        raise MetadataError("all release.json values must be strings")
    if VERSION_PATTERN.fullmatch(value["productVersion"]) is None:
        raise MetadataError("productVersion must contain 2 to 4 numeric components")
    if BUILD_PATTERN.fullmatch(value["buildNumber"]) is None:
        raise MetadataError("buildNumber must be a positive base-10 integer")
    if value["releaseChannel"] not in {"stable", "prerelease"}:
        raise MetadataError("releaseChannel must be stable or prerelease")
    return value


def generated_swift(metadata: dict[str, str]) -> str:
    prerelease = "true" if metadata["releaseChannel"] == "prerelease" else "false"
    return f'''// Generated by scripts/release_metadata.py from config/release.json.
// Do not edit this file directly.

public enum GeneratedReleaseMetadata {{
    public static let productVersion = "{metadata["productVersion"]}"
    public static let buildNumber = "{metadata["buildNumber"]}"
    public static let releaseChannel = "{metadata["releaseChannel"]}"
    public static let isPrerelease = {prerelease}
}}
'''


def generated_readme(source: str, name: str, metadata: dict[str, str]) -> str:
    expected = README_BADGES[name].format(version=metadata["productVersion"])
    marker_index = source.find(README_MARKER)
    if marker_index < 0:
        raise MetadataError(f"{name} is missing the generated release badge marker")
    second_marker = source.find(README_MARKER, marker_index + len(README_MARKER))
    if second_marker >= 0:
        raise MetadataError(f"{name} contains more than one generated release badge marker")
    line_end = source.find("\n", marker_index)
    if line_end < 0:
        raise MetadataError(f"{name} release badge marker has no following line")
    badge_end = source.find("\n", line_end + 1)
    if badge_end < 0:
        badge_end = len(source)
    current_badge = source[line_end + 1 : badge_end]
    if "img.shields.io/badge/" not in current_badge:
        raise MetadataError(f"{name} release badge marker is not followed by a badge")
    return source[: line_end + 1] + expected + source[badge_end:]


def expected_files(root: pathlib.Path, metadata: dict[str, str]) -> dict[pathlib.Path, str]:
    outputs = {
        root / "Sources" / "MediaLibServerProtocol" / "GeneratedReleaseMetadata.swift": generated_swift(metadata)
    }
    for name in README_BADGES:
        path = root / name
        try:
            source = path.read_text(encoding="utf-8")
        except OSError as error:
            raise MetadataError(f"cannot read {path}: {error}") from error
        outputs[path] = generated_readme(source, name, metadata)
    return outputs


def atomic_write(path: pathlib.Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_name, path)
    except BaseException:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise


def write_outputs(root: pathlib.Path, metadata: dict[str, str]) -> None:
    for path, expected in expected_files(root, metadata).items():
        atomic_write(path, expected.encode("utf-8"))


def check_outputs(root: pathlib.Path, metadata: dict[str, str]) -> None:
    stale: list[str] = []
    for path, expected in expected_files(root, metadata).items():
        try:
            actual = path.read_text(encoding="utf-8")
        except OSError:
            actual = ""
        if actual != expected:
            stale.append(str(path.relative_to(root)))
    if stale:
        joined = ", ".join(stale)
        raise MetadataError(
            f"generated release metadata is stale: {joined}; run scripts/release_metadata.py --write"
        )


def write_info_plist(path: pathlib.Path, metadata: dict[str, str]) -> None:
    try:
        with path.open("rb") as handle:
            value = plistlib.load(handle)
    except (OSError, plistlib.InvalidFileException) as error:
        raise MetadataError(f"cannot read Info.plist at {path}: {error}") from error
    if not isinstance(value, dict):
        raise MetadataError("Info.plist root must be a dictionary")
    value["CFBundleShortVersionString"] = metadata["productVersion"]
    value["CFBundleVersion"] = metadata["buildNumber"]
    value["MediaLibReleaseChannel"] = metadata["releaseChannel"]
    atomic_write(path, plistlib.dumps(value, fmt=plistlib.FMT_XML, sort_keys=False))


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=pathlib.Path, default=pathlib.Path(__file__).resolve().parent.parent)
    actions = parser.add_mutually_exclusive_group(required=True)
    actions.add_argument("--write", action="store_true")
    actions.add_argument("--check", action="store_true")
    actions.add_argument("--get", choices=sorted(CONFIG_KEYS))
    actions.add_argument("--write-info-plist", type=pathlib.Path)
    return parser.parse_args()


def main() -> int:
    arguments = parse_arguments()
    root = arguments.root.resolve()
    try:
        metadata = load_metadata(root)
        if arguments.write:
            write_outputs(root, metadata)
            print(f"release metadata generated for {metadata['productVersion']} ({metadata['buildNumber']})")
        elif arguments.check:
            check_outputs(root, metadata)
            print(f"release metadata is current: {metadata['productVersion']} ({metadata['buildNumber']})")
        elif arguments.get:
            print(metadata[arguments.get])
        elif arguments.write_info_plist:
            write_info_plist(arguments.write_info_plist, metadata)
    except MetadataError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
